// components/Layout.tsx
import React, { useEffect } from 'react'
import { Container } from '@chakra-ui/react'
import Header from './Header'
import 'prismjs/themes/prism.css'
import 'katex/dist/katex.min.css'
import { useRouter } from 'next/router'

const Layout: React.FC = ({ children }) => {
  const { pathname } = useRouter()

  useEffect(() => {
    ;(async () => {
      const renderMathInElement = (
        await import('katex/dist/contrib/auto-render')
      ).default

      renderMathInElement(document.body, {
        delimiters: [
          { left: '$$', right: '$$', display: true },
          { left: '$', right: '$', display: false },
        ],
      })
    })()
  }, [pathname])

  useEffect(() => {
    ;(async () => {
      const Viz = (await import('viz.js')).default
      // @ts-ignore
      const { Module, render } = await import('viz.js/full.render')

      const viz = new Viz({ Module, render })

      const nodes: NodeListOf<HTMLElement> = document.querySelectorAll(
        '[class=language-dot]'
      )
      nodes.forEach(async (el) => {
        if (el.style.display === 'none') {
          return
        }
        const data = el.innerText.replaceAll('&quot;', '"')

        const svg = await viz.renderSVGElement(data, {
          format: 'svg',
          engine: 'dot',
        })

        const parentElement = el.parentElement
        if (!parentElement || !parentElement.parentElement) {
          return
        }

        parentElement?.parentElement.insertBefore(svg, parentElement)
        parentElement.style.display = 'none'
      })
    })()
  }, [pathname])

  return (
    <>
      <Header
        borderBottom="1px"
        borderBottomColor="gray.200"
        position="fixed"
        width="100%"
        top="0"
        zIndex="2"
      />
      <Container as="main" maxW="container.md" mt="14" py="4">
        {children}
      </Container>
    </>
  )
}

export default Layout

// docs/.vuepress/theme/layouts/Layout.vue
<template>
  <ParentLayout>
    <slot name="page-top" slot="page-top" />
  </ParentLayout>
</template>

<script>
import ParentLayout from '@parent-theme/layouts/Layout.vue'
import renderMathInElement from 'katex/contrib/auto-render/auto-render';

export default {
  components: {
    ParentLayout,
  },
  mounted() {
    this.renderKatex()
    this.renderViz()
    this.$router.afterEach(() => {
      requestAnimationFrame(() => {
        this.renderKatex()
        this.renderViz()
      })
    })
  },
  methods: {
    renderKatex() {
      renderMathInElement(document.body, {
        delimiters: [
            {left: "$$", right: "$$", display: true},
            {left: "$", right: "$", display: false}
          ]
        }
      );
    },
    renderViz() {
      var vizPrefix = "language-viz-";
      var nodes = document.querySelectorAll("[class^=" + vizPrefix + "]");

      Array.prototype.forEach.call(nodes, function(x) {
        if(x.style.display === "none") {
          return;
        }

        var engine;
        x.getAttribute("class").split(" ").forEach(function(cls) {
          if (cls.startsWith(vizPrefix)) {
            engine = cls.substr(vizPrefix.length);
          }
        });

        var viz = new Viz();
        const req = viz.renderSVGElement(x.innerText, {format: "svg", engine: engine})
        req.then(svg => {
          svg.classList.add ("viz-svg");
    
          x.parentNode.insertBefore(svg, x);
          x.style.display = 'none';
          x.parentNode.style.backgroundColor = "white";
        })
      });
    }
  }
}
</script>

<style lang="stylus">
@import '../../../../node_modules/katex/dist/katex.min.css';

.viz-svg {
  margin: auto;
  display: block;
  max-width: 100%;
}
</style>
